[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=Click OK to install SENTINEL v1.0.3
DisplayLicense=C:\Users\matth\Desktop\sentinal\LICENSE.txt
FinishMessage=SENTINEL has been installed successfully!
TargetName=C:\Users\matth\Desktop\sentinal\dist\SENTINEL-v1.0.3-Setup.exe
FriendlyName=SENTINEL v1.0.3 Setup
AppLaunched=cmd /c install.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="sentinel-win-x64.exe"
FILE1="install.bat"
FILE2="README.txt"
[SourceFiles]
SourceFiles0=C:\Users\matth\Desktop\sentinal\dist\
SourceFiles1=C:\Users\matth\Desktop\sentinal\installer\
SourceFiles2=C:\Users\matth\Desktop\sentinal\
[SourceFiles0]
%FILE0%=
[SourceFiles1]
%FILE1%=
[SourceFiles2]
%FILE2%=
