[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=Welcome to SENTINEL v1.0.3 Setup. Click OK to continue.
DisplayLicense=C:\Users\matth\Desktop\sentinal\LICENSE.txt
FinishMessage=SENTINEL has been installed successfully!
TargetName=C:\Users\matth\Desktop\sentinal\dist\SENTINEL-v1.0.3-Setup.exe
FriendlyName=SENTINEL v1.0.3 Setup
AppLaunched=install.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="install.bat"
FILE1="README.txt"
FILE2="sentinel-win-x64.exe"
[SourceFiles]
SourceFiles0=C:\Users\matth\AppData\Local\Temp\sentinel-installer\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
